-- AlterTable
ALTER TABLE "Click" ALTER COLUMN "clicked_at" SET DATA TYPE TIMESTAMPTZ;

-- AlterTable
ALTER TABLE "Url" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ,
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMPTZ;
